version: "3.9"
services:
  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  app:
    build: .  
    ports:
      - "8000:8000"  
    environment:
      POSTGRESQL_DATABASE_URL: ${POSTGRESQL_DATABASE_URL}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
    depends_on:
      - db 

volumes:
  db_data: